# Setup
title: Have Hill
description: Sookmyung w.univ Statistics & Artificial Intelligence
url: https://havehill.github.io/blog/
avatar: /profile.jpg
paginate: 5
permalink: pretty
cover_image: /cover.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: havehill
  card: summary
logo: logo.png
social:
  name: havehill
  links:
    - https://instargram.com/have_hill
    - https://github.com/havehill
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Jaewon Jung
  url: https://github.com/havehill/
  email: havehill@sookmyung.ac.kr

remote_theme: benbalter/retlab
